server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "rpa-bot-json-logs"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "rpa-normalizador-cuentas"
          __path__: /var/log/bot/*.jsonl

    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            bot: bot_name
            run: run_id
            step: step
            msg: message

      # Convert timestamp to Grafana format
      - timestamp:
          source: ts
          format: RFC3339

      # Promtail labels
      - labels:
          level:
          bot:
          run:
          step: